### ISSUE TITLE
Energy mismatch between tblite and xtb

### ISSUE THREAD

**Issue by pchliu** [tblite/tblite#114] opened 2023-06-08 03:39 UTC
Hi all,

I'm running into a rather peculiar issue. I'm running a single point calculation with tblite and xtb using the same Hamiltonian (and I believe similar parameters) for the same geometry, but the energies differ by an order of magnitude. 

the tblite code: 
```python
import numpy as np
from tblite.interface import Calculator

numbers = np.array([6, 6, 6, 8, 7, 6, 7, 6, 8, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
positions = np.array(
    [
    [ 0.46536168,  0.51302998,  2.03981721],
    [-0.02177816,  0.48537017,  0.59805075],
    [ 1.01101740, -0.24432523, -0.28335925],
    [ 2.05332842, -0.71073985,  0.17590989],
    [ 0.70094176, -0.26161425, -1.62922601],
    [ 1.53298011, -0.98387001, -2.55844058],
    [-1.29076540, -0.22637927,  0.49605519],
    [-1.86891780, -0.75698853,  1.62811605],
    [-1.29564014, -0.84098708,  2.70946947],
    [-3.28438411, -1.22862121,  1.43104119],
    [ 0.62560153, -0.50053914,  2.42499647],
    [-0.26829730,  1.00348012,  2.68838186],
    [ 1.41378224,  1.05362627,  2.1257442 ],
    [-0.14478926,  1.51051215,  0.2313505 ],
    [-0.26674592, -0.11192939, -1.88761009],
    [ 1.35494639, -2.05497009, -2.43072288],
    [ 2.58757392, -0.76523253, -2.37012068],
    [ 1.26459022, -0.68129800, -3.57313037],
    [-1.93637095,  0.15942386, -0.18519414],
    [-3.40082539, -2.21353625,  1.89162281],
    [-3.53441518, -1.31602648,  0.36992353],
    [-3.96747765, -0.51699443,  1.9018549 ]]
)
calc = Calculator("GFN2-xTB", numbers, positions)
calc.set('verbosity', 2)
res = calc.singlepoint()
res.get("energy")
```

The xtb command is simply `xtb --gfn 2 example_conformer.xyz`, where `example_conformer.xyz` is:
```
22

C      0.465362    0.513030    2.039817
C     -0.021778    0.485370    0.598051
C      1.011017   -0.244325   -0.283359
O      2.053328   -0.710740    0.175910
N      0.700942   -0.261614   -1.629226
C      1.532980   -0.983870   -2.558441
N     -1.290765   -0.226379    0.496055
C     -1.868918   -0.756989    1.628116
O     -1.295640   -0.840987    2.709469
C     -3.284384   -1.228621    1.431041
H      0.625602   -0.500539    2.424996
H     -0.268297    1.003480    2.688382
H      1.413782    1.053626    2.125744
H     -0.144789    1.510512    0.231351
H     -0.266746   -0.111929   -1.887610
H      1.354946   -2.054970   -2.430723
H      2.587574   -0.765233   -2.370121
H      1.264590   -0.681298   -3.573130
H     -1.936371    0.159424   -0.185194
H     -3.400825   -2.213536    1.891623
H     -3.534415   -1.316026    0.369924
H     -3.967478   -0.516994    1.901855
```

The result of tblite is 
```
repulsion energy          2.1948857688246E+01 Eh
dispersion energy         5.9727674718367E-06 Eh
number of electrons       5.8000000000000E+01 e
integral cutoff           1.7347787504999E+01 bohr

------------------------------------------------------------
  cycle        total energy    energy error   density error
------------------------------------------------------------
      1     -3.326418302892  -2.5275282E+01   3.9045950E-01
      2     -3.414151912374  -8.7733609E-02   2.3229372E-01
      3     -3.449861172378  -3.5709260E-02   3.4762319E-02
      4     -3.452876452920  -3.0152805E-03   1.0570224E-02
      5     -3.452977637599  -1.0118468E-04   4.8300865E-03
      6     -3.452992491959  -1.4854360E-05   1.0162407E-03
      7     -3.452994198028  -1.7060698E-06   2.0715386E-04
      8     -3.452994316551  -1.1852226E-07   6.2101748E-05
      9     -3.452994322897  -6.3465038E-09   1.6878293E-05
------------------------------------------------------------

electronic energy        -2.5401857983910E+01 Eh
total energy             -3.4529943228972E+00 Eh

 total:                                   0.053 sec
 - repulsion                              0.000 sec (  0%)
 - dispersion                             0.001 sec (  1%)
 - coulomb                                0.001 sec (  1%)
 - hamiltonian                            0.003 sec (  5%)
 - scc                                    0.048 sec ( 90%)

array(-3.45299432)
```

whereas for xtb, it is:
```
      -----------------------------------------------------------      
     |                   =====================                   |     
     |                           x T B                           |     
     |                   =====================                   |     
     |                         S. Grimme                         |     
     |          Mulliken Center for Theoretical Chemistry        |     
     |                    University of Bonn                     |     
      -----------------------------------------------------------      

   * xtb version 6.5.1 (conda-forge) compiled by 'runner@Mac-1672870425861.local' on 2023-01-04
 * started run on 2023/06/07 at 11:30:52.718     

           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : xtb --gfn 2 example_conformer.xyz
          coordinate file            : example_conformer.xyz
          omp threads                :                    12

   ID    Z sym.   atoms
    1    6 C      1-3, 6, 8, 10
    2    8 O      4, 9
    3    7 N      5, 7
    4    1 H      11-22

           -------------------------------------------------
          |                 G F N 2 - x T B                 |
           -------------------------------------------------

        Reference                      10.1021/acs.jctc.8b01176
      * Hamiltonian:
        H0-scaling (s, p, d)           1.850000    2.230000    2.230000
        zeta-weighting                 0.500000
      * Dispersion:
        s8                             2.700000
        a1                             0.520000
        a2                             5.000000
        s9                             5.000000
      * Repulsion:
        kExp                           1.500000    1.000000
        rExp                           1.000000
      * Coulomb:
        alpha                          2.000000
        third order                    shell-resolved
        anisotropic                    true
        a3                             3.000000
        a5                             4.000000
        cn-shift                       1.200000
        cn-exp                         4.000000
        max-rad                        5.000000


          ...................................................
          :                      SETUP                      :
          :.................................................:
          :  # basis functions                  52          :
          :  # atomic orbitals                  52          :
          :  # shells                           32          :
          :  # electrons                        58          :
          :  max. iterations                   250          :
          :  Hamiltonian                  GFN2-xTB          :
          :  restarted?                      false          :
          :  GBSA solvation                  false          :
          :  PC potential                    false          :
          :  electronic temp.          300.0000000     K    :
          :  accuracy                    1.0000000          :
          :  -> integral cutoff          0.2500000E+02      :
          :  -> integral neglect         0.1000000E-07      :
          :  -> SCF convergence          0.1000000E-05 Eh   :
          :  -> wf. convergence          0.1000000E-03 e    :
          :  Broyden damping             0.4000000          :
          ...................................................

 iter      E             dE          RMSdq      gap      omega  full diag
   1    -33.1841955 -0.331842E+02  0.397E+00    4.51       0.0  T
   2    -33.2909013 -0.106706E+00  0.217E+00    3.98       1.0  T
   3    -33.2989168 -0.801555E-02  0.128E+00    4.26       1.0  T
   4    -33.2997760 -0.859151E-03  0.255E-01    4.01       1.0  T
   5    -33.3008702 -0.109419E-02  0.950E-02    4.10       1.0  T
   6    -33.3008765 -0.628795E-05  0.395E-02    4.10       1.0  T
   7    -33.3008811 -0.457897E-05  0.116E-02    4.09       1.8  T
   8    -33.3008817 -0.666106E-06  0.511E-03    4.09       4.2  T
   9    -33.3008819 -0.154518E-06  0.189E-03    4.09      11.3  T
  10    -33.3008819 -0.141989E-07  0.863E-04    4.09      24.7  T
  11    -33.3008819 -0.615695E-08  0.211E-04    4.09     101.3  T

   *** convergence criteria satisfied after 11 iterations ***

         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         ::                     SUMMARY                     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         :: total energy             -32.934546246331 Eh    ::
         :: gradient norm              0.087059518504 Eh/a0 ::
         :: HOMO-LUMO gap              4.093275958748 eV    ::
         ::.................................................::
         :: SCC energy               -33.300881891377 Eh    ::
         :: -> isotropic ES            0.074562117470 Eh    ::
         :: -> anisotropic ES          0.008257246992 Eh    ::
         :: -> anisotropic XC          0.011935644504 Eh    ::
         :: -> dispersion             -0.015403472051 Eh    ::
         :: repulsion energy           0.366261553838 Eh    ::
         :: add. restraining           0.000000000000 Eh    ::
         :: total charge              -0.000000000000 e     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::

           -------------------------------------------------
          | TOTAL ENERGY              -32.934546246331 Eh   |
          | GRADIENT NORM               0.087059518504 Eh/α |
          | HOMO-LUMO GAP               4.093275958748 eV   |
           -------------------------------------------------

normal termination of xtb
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
```

Thank you in advance!

**Comment by awvwgk** [comment] 2023-06-08 06:02
Both xtb and tblite internally use Bohr as a length unit. When using the API be sure to do the conversion from Angstrom first, the CLI for both programs will do the conversion for you if an XYZ file is provided as input.

**Comment by awvwgk** [comment] 2024-01-08 21:59
Closing this issue since this is the expected behavior

**Closed as completed by awvwgk** 2024-01-08 21:59 UTC
