### ISSUE TITLE
Handling f-in-core

### ISSUE THREAD

**Issue by corinwagen** [tblite/tblite#200] opened 2024-08-21 17:47 UTC
Following up from crest-lab/crest#334 (thanks @pprcht), I'm trying to understand what happens to the `uhf` parameter that gets passed to `tblite` from CREST. (I've noticed a change between CREST 2.12 and CREST 3.0.1, as detailed at the above issue.)

When I try to run tblite on the Ce complex from there, my command-line `uhf` argument seems to just get ignored? 

```
$ tblite run --method gfn2 --spin 0 --charge 0 -- Ce_NTf2_3_H2O_3.xyz
xTB calculator
 | screened Coulomb repulsion
 | Coulomb electrostatics
 |  * isotropic Klopman-Ohno electrostatics
 |  * anisotropic electrostatics
 |  * onsite third-order electrostatics
 | self-consistent DFT-D4 dispersion

repulsion energy          7.1080750216502E-01 Eh
dispersion energy         4.5529180240471E-03 Eh
number of electrons       3.0000000000000E+02 e
integral cutoff           3.9349873946655E+01 bohr

------------------------------------------------------------
  cycle        total energy    energy error   density error
------------------------------------------------------------
      1     -189.5085160897  -1.9022388E+02   3.4338697E-01
      2     -191.6812814470  -2.1727654E+00   2.0557432E-01
      3     -191.8386705532  -1.5738911E-01   1.1807400E-01
      4     -191.8861802183  -4.7509665E-02   5.8583212E-02
      5     -191.8951025719  -8.9223536E-03   3.2185856E-02
      6     -191.8999238912  -4.8213193E-03   1.2919773E-02
      7     -191.9002739782  -3.5008703E-04   6.3124895E-03
      8     -191.9004484081  -1.7442986E-04   2.4837868E-03
      9     -191.9004844744  -3.6066357E-05   1.1526719E-03
     10     -191.9004962186  -1.1744132E-05   4.9916159E-04
     11     -191.9004982292  -2.0106645E-06   2.2054360E-04
     12     -191.9004985869  -3.5766740E-07   7.6103650E-05
     13     -191.9004986250  -3.8136250E-08   3.6508108E-05
     14     -191.9004986359  -1.0887675E-08   8.2136303E-06
------------------------------------------------------------

electronic energy        -1.9261585905612E+02 Eh
total energy             -1.9190049863593E+02 Eh

 total:                                   0.411 sec
 - repulsion                              0.000 sec (  0%)
 - dispersion                             0.002 sec (  0%)
 - coulomb                                0.001 sec (  0%)
 - hamiltonian                            0.005 sec (  1%)
 - scc                                    0.402 sec ( 97%)

$ tblite run --method gfn2 --spin 1 --charge 0 -- Ce_NTf2_3_H2O_3.xyz
xTB calculator
 | screened Coulomb repulsion
 | Coulomb electrostatics
 |  * isotropic Klopman-Ohno electrostatics
 |  * anisotropic electrostatics
 |  * onsite third-order electrostatics
 | self-consistent DFT-D4 dispersion

repulsion energy          7.1080750216502E-01 Eh
dispersion energy         4.5529180240471E-03 Eh
number of electrons       3.0000000000000E+02 e
integral cutoff           3.9349873946655E+01 bohr

------------------------------------------------------------
  cycle        total energy    energy error   density error
------------------------------------------------------------
      1     -189.5085160897  -1.9022388E+02   3.4338697E-01
      2     -191.6812814470  -2.1727654E+00   2.0557432E-01
      3     -191.8386705532  -1.5738911E-01   1.1807400E-01
      4     -191.8861802183  -4.7509665E-02   5.8583212E-02
      5     -191.8951025719  -8.9223536E-03   3.2185856E-02
      6     -191.8999238912  -4.8213193E-03   1.2919773E-02
      7     -191.9002739782  -3.5008703E-04   6.3124895E-03
      8     -191.9004484081  -1.7442986E-04   2.4837868E-03
      9     -191.9004844744  -3.6066357E-05   1.1526719E-03
     10     -191.9004962186  -1.1744132E-05   4.9916159E-04
     11     -191.9004982292  -2.0106644E-06   2.2054360E-04
     12     -191.9004985869  -3.5766737E-07   7.6103650E-05
     13     -191.9004986250  -3.8136307E-08   3.6508108E-05
     14     -191.9004986359  -1.0887589E-08   8.2136303E-06
------------------------------------------------------------

electronic energy        -1.9261585905612E+02 Eh
total energy             -1.9190049863593E+02 Eh

 total:                                   0.549 sec
 - repulsion                              0.000 sec (  0%)
 - dispersion                             0.001 sec (  0%)
 - coulomb                                0.001 sec (  0%)
 - hamiltonian                            0.005 sec (  0%)
 - scc                                    0.541 sec ( 98%)
$ tblite --version
tblite version 0.3.0
```

The energy seems exactly the same between the two runs. What happens with lanthanides and the spin multiplicities here, and is there any reason why this should have changed between CREST versions? 

Possible precedent here: #112, #151

**Comment by awvwgk** [comment] 2024-11-17 19:09
Thanks for bringing this up. The lanthanides are indeed handled with f-in-core, which can lead to some unexpected behaviors especially with Cer, which now only has 3 instead of 4 valence electrons. Here the f-in-core approximation is arguably incorrect as we cannot represent the Cer in the +IV oxidation state anymore.

Generally, *xtb* tends to ignore incorrect number of unpaired electrons, *tblite* followed this behavior before but it will be changed in the future and the *tblite* calculation will fail if the multiplicity does not match. As for the change in *crest* from v2 to v3 there is a change from *xtb* to *tblite* involved. Hopefully in the future *tblite* can provide more meaningful error messages for incorrect numbers of unpaired electrons in *crest*.

Since I don't see anything actionable on the *tblite* side here, except maybe for reparametrizing Cer to support 4 valence electrons, I will close this as resolved. Feel free to open a new issue if anything is left unaddressed.

**Closed as completed** 2024-11-17 19:12 UTC
