### ISSUE TITLE
Issues with meson build

### ISSUE THREAD

**Issue by gavinwinter** [tblite/tblite#36] opened 2022-05-11 02:54 UTC
I am trying to install the python API and having difficulties. I first tried a pip install to install the python API interface with an existing tblite installation. I got the error that this import couldn't be made `from ._libtblite import ffi, lib`  when loading python/tblite/library.py. Indeed the file `_libtblite` was located nowhere. Since building on top didn't work, I then proceeded to delete everything and start over using the recommended meson build method. I'm using meson version 0.59.0, which satisfies the suggested requirements > 0.55.0. Unfortunately ,cloning this git repo and trying `meson setup _build -Dpython_version=3` immediately yields the following error:
```
Traceback (most recent call last):
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 227, in run
    return options.run_func(options)
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/msetup.py", line 281, in run
    app.generate()
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/msetup.py", line 183, in generate
    with mesonlib.BuildDirLock(self.build_dir):
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/mesonlib/posix.py", line 32, in __enter__
    fcntl.flock(self.lockfile, fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 38] Function not implemented
```
In my environment containing `meson`, I am able to `import fcntl` in a python session. Any ideas on what either of my problems here are caused by?

**Comment by awvwgk** [comment] 2022-05-15 10:05
To help with this issue I need a little bit more information, like the commands you used and the full error messages received.

**Comment by gavinwinter** [comment] 2022-05-15 12:43
You should be able to replicate the error by (1) creating a new conda environment and installing meson 0.59.0 through conda, (2) git cloning this tblite repo, and (3) trying `meson setup _build -Dpython_version=3` with the new conda environment containing meson activated. It should give the following error:
```
Traceback (most recent call last):
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 227, in run
    return options.run_func(options)
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/msetup.py", line 281, in run
    app.generate()
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/msetup.py", line 183, in generate
    with mesonlib.BuildDirLock(self.build_dir):
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/mesonlib/posix.py", line 32, in __enter__
    fcntl.flock(self.lockfile, fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 38] Function not implemented
```
I also tried downgrading to meson 0.55.0, but got the same error upon trying `meson setup _build -Dpython_version=3`.

**Comment by awvwgk** [comment] 2022-05-15 12:52
Sorry, cannot reproduce this issue with my setup, note that the `-Dpython_version` option is only required in case of multiple parallel Python installations.

```
❯ mamba list
# packages in environment at /home/awvwgk/software/opt/conda/envs/tblite:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cffi                      1.15.0          py310h0fdd8cc_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
meson                     0.59.0             pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ninja                     1.10.2               h4bd325d_1    conda-forge
openssl                   3.0.3                h166bdaf_0    conda-forge
pip                       22.1               pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
python                    3.10.4          h2660328_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                62.2.0          py310hff52083_0    conda-forge
sqlite                    3.38.5               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
❯ mkdir ~/example
❯ git clone git@github.com:tblite/tblite ~/example/tblite
❯ meson setup ~/example/tblite/_build ~/example/tblite -Dpython=true
...
Build targets in project: 32

tblite 0.2.0

  Subprojects
    dftd4             : YES
    json-fortran-8.2.5: YES
    mctc-lib          : YES
    mstore            : YES
    multicharge       : YES
    s-dftd3           : YES 1 warnings
    toml-f            : YES

Found ninja-1.10.2 at /home/awvwgk/software/opt/conda/envs/tblite/bin/ninja
❯ echo $?
0
```

If you can clarify what is not working in your setup, I might be able to provide help.

**Comment by awvwgk** [comment] 2022-05-15 12:58
I just setup a manylinux Python wheel build on my fork of tblite. You could download the matching Python wheel from the _Artifacts_ panel at https://github.com/awvwgk/tblite/actions/runs/2327101334 and install it directly with `pip install *.whl`.

**Comment by gavinwinter** [comment] 2022-05-15 13:35
I have the same packages as you now and still have the same error. A few of the versions are slightly different, but per the installation instructions this does not seem like it should be the problem.

```

(meson) gawinter@login-4:~/projects/xtb/tblite$ conda list
# packages in environment at /home/gridsan/gawinter/.conda/envs/meson:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2022.4.26            h06a4308_0
certifi                   2021.10.8        py39h06a4308_2
cffi                      1.15.0           py39hd667e15_1
ld_impl_linux-64          2.38                 h1181459_0
libffi                    3.3                  he6710b0_2
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17
libuuid                   1.0.3                h7f8727e_2
libzlib                   1.2.11            h166bdaf_1014    conda-forge
llvm-openmp               14.0.3               he0ac6c6_0    conda-forge
meson                     0.59.0             pyhd3eb1b0_0
ncurses                   6.3                  h7f8727e_2
ninja                     1.10.2               h06a4308_5
ninja-base                1.10.2               hd09550d_5
openssl                   1.1.1o               h7f8727e_0
pip                       21.2.4           py39h06a4308_0
pycparser                 2.21               pyhd3eb1b0_0
python                    3.9.12               h12debd9_0
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1.2                h7f8727e_1
setuptools                61.2.0           py39h06a4308_0
sqlite                    3.38.2               hc218d9a_0
tk                        8.6.11               h1ccaba5_0
tzdata                    2022a                hda174b7_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.5                h7f8727e_1
zlib                      1.2.11            h166bdaf_1014    conda-forge
(meson) gawinter@login-4:~/projects/xtb/tblite$ ls
CMakeLists.txt  COPYING  COPYING.LESSER  README.md  app  config  doc  fpm.toml  include  man  meson.build  meson_options.txt  python  src  subprojects  test
(meson) gawinter@login-4:~/projects/xtb/tblite$ meson setup _build -Dpython=true
Traceback (most recent call last):
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 227, in run
    return options.run_func(options)
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/msetup.py", line 281, in run
    app.generate()
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/msetup.py", line 183, in generate
    with mesonlib.BuildDirLock(self.build_dir):
  File "/home/gridsan/gawinter/.conda/envs/meson/lib/python3.9/site-packages/mesonbuild/mesonlib/posix.py", line 32, in __enter__
    fcntl.flock(self.lockfile, fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 38] Function not implemented
(meson) gawinter@login-4:~/projects/xtb/tblite$
```

**Comment by gavinwinter** [comment] 2022-05-15 13:45
I did just try building from the wheel and that worked as a quick fix

**Comment by awvwgk** [comment] 2022-05-15 13:48
This does seem like a meson / Python error rather than something related to this project. Best check with your local sysadmin on this issue.

**Comment by eli-schwartz** [comment] 2022-05-15 15:55
Meson itself is trying to use https://docs.python.org/3/library/fcntl.html but apparently that does not work on your system for some reason?

**Comment by awvwgk** [comment] 2022-05-21 11:58
I just released a new version including a free-standing Python sdist using [`meson-python`](https://meson-python.rtfd.io) as build backend. Hope this simplifies installing the Python bindings.

**Comment by awvwgk** [comment] 2022-06-03 15:10
Closing this as resolved. Feel free to reopen if that is not the case.

**Closed as completed by awvwgk** 2022-06-03 15:10 UTC
Labels: build
