### ISSUE TITLE
Inlined transformation matrix uses wrong orbital ordering

### ISSUE THREAD

**Issue by marvinfriede** [tblite/tblite#104] opened 2023-03-28 11:57 UTC
If one uses the [transformation matrix](https://github.com/tblite/tblite/blob/b3dcf324366eb053d41bd15af15b4a2d26487a4a/src/tblite/integral/trafo.f90#L33) for the transformation from cartesian to spherical basis functions, many tests throw an error. To be precise, using `sphr = matmul(dtrafo, matmul(cart, transpose(dtrafo)))` does not yield the same result as the [explicit transformation](https://github.com/tblite/tblite/blob/b3dcf324366eb053d41bd15af15b4a2d26487a4a/src/tblite/integral/trafo.f90#L135).
If I change the ordering from `[-l, ..., 0, ..., l]` to `[0, ..., l-1, -(l-1), l, -l]`, it works again.

```fortran
real(wp), parameter :: dtrafo(5, 6) = reshape([&
   !  0       1       -1      2       -2
   & -0.5_wp, 0.0_wp, 0.0_wp,   s3_4, 0.0_wp, & ! xx
   & -0.5_wp, 0.0_wp, 0.0_wp,  -s3_4, 0.0_wp, & ! yy
   &  1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, & ! zz
   &  0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp,     s3, & ! xy
   &  0.0_wp,     s3, 0.0_wp, 0.0_wp, 0.0_wp, & ! xz
   &  0.0_wp, 0.0_wp,     s3, 0.0_wp, 0.0_wp],& ! yz
   & shape(dtrafo))
```

I suspect that the same applies to the transformation matrices for higher (than 2) angular momenta.

**Comment by awvwgk** [comment] 2023-07-26 08:16
Failing tests with explicit transformation matrices:

````
# Testing: integral-overlap
  Starting overlap-1 ... (1/11)
       ... overlap-1 [FAILED]
  Message: Floating point value missmatch
  Starting overlap-5 ... (5/11)
       ... overlap-5 [FAILED]
  Message: Floating point value missmatch
# Testing: hamiltonian
  Starting hamiltonian-3 ... (3/4)
 0.0000000000000E+00-2.0595187670703E-01
 2.0595187670703E-01
       ... hamiltonian-3 [FAILED]
  Message: Floating point value missmatch
  Starting hamiltonian-4 ... (4/4)
-1.2391237859785E-01 0.0000000000000E+00
-1.2391237859785E-01
       ... hamiltonian-4 [FAILED]
  Message: Floating point value missmatch
````

Looks like the ordering from -l, ..., 0, ..., +l is not correctly reflected in the inlined expressions.

<details><summary>patch for reproducing</summary>

````patch
diff --git a/src/tblite/integral/trafo.f90 b/src/tblite/integral/trafo.f90
index ae98ac3..c013a77 100644
--- a/src/tblite/integral/trafo.f90
+++ b/src/tblite/integral/trafo.f90
@@ -107,12 +107,12 @@ pure subroutine transform0(lj, li, cart, sphr)
       case(0, 1)
          sphr = cart
       case(2)
-         ! sphr = matmul(dtrafo, cart)
-         sphr(1, :) = cart(3, :) - 0.5_wp * (cart(1, :) + cart(2, :))
-         sphr(2, :) = s3 * cart(5, :)
-         sphr(3, :) = s3 * cart(6, :)
-         sphr(4, :) = s3_4 * (cart(1, :) - cart(2, :))
-         sphr(5, :) = s3 * cart(4, :)
+         sphr = matmul(dtrafo, cart)
+         ! sphr(1, :) = cart(3, :) - 0.5_wp * (cart(1, :) + cart(2, :))
+         ! sphr(2, :) = s3 * cart(5, :)
+         ! sphr(3, :) = s3 * cart(6, :)
+         ! sphr(4, :) = s3_4 * (cart(1, :) - cart(2, :))
+         ! sphr(5, :) = s3 * cart(4, :)
       case(3)
          sphr = matmul(ftrafo, cart)
       case(4)
@@ -124,34 +124,34 @@ pure subroutine transform0(lj, li, cart, sphr)
    case(2)
       select case(lj)
       case(0, 1)
-         ! sphr = matmul(cart, transpose(dtrafo))
-         sphr(:, 1) = cart(:, 3) - 0.5_wp * (cart(:, 1) + cart(:, 2))
-         sphr(:, 2) = s3 * cart(:, 5)
-         sphr(:, 3) = s3 * cart(:, 6)
-         sphr(:, 4) = s3_4 * (cart(:, 1) - cart(:, 2))
-         sphr(:, 5) = s3 * cart(:, 4)
+         sphr = matmul(cart, transpose(dtrafo))
+         ! sphr(:, 1) = cart(:, 3) - 0.5_wp * (cart(:, 1) + cart(:, 2))
+         ! sphr(:, 2) = s3 * cart(:, 5)
+         ! sphr(:, 3) = s3 * cart(:, 6)
+         ! sphr(:, 4) = s3_4 * (cart(:, 1) - cart(:, 2))
+         ! sphr(:, 5) = s3 * cart(:, 4)
       case(2)
-         ! sphr = matmul(dtrafo, matmul(cart, transpose(dtrafo)))
-         sphr(1, 1) = cart(3, 3) &
-            & - 0.5_wp * (cart(3, 1) + cart(3, 2) + cart(1, 3) + cart(2, 3)) &
-            & + 0.25_wp * (cart(1, 1) + cart(1, 2) + cart(2, 1) + cart(2, 2))
-         sphr([2, 3, 5], 1) = s3 * cart([5, 6, 4], 3) &
-            & - s3_4 * (cart([5, 6, 4], 1) + cart([5, 6, 4], 2))
-         sphr(4, 1) = s3_4 * (cart(1, 3) - cart(2, 3)) &
-            & - s3 * 0.25_wp * (cart(1, 1) - cart(2, 1) + cart(1, 2) - cart(2, 2))
-         sphr(1, 2) = s3 * cart(3, 5) - s3_4 * (cart(1, 5) + cart(2, 5))
-         sphr([2, 3, 5], 2) = 3 * cart([5, 6, 4], 5)
-         sphr(4, 2) = 1.5_wp * (cart(1, 5) - cart(2, 5))
-         sphr(1, 3) = s3 * cart(3, 6) - s3_4 * (cart(1, 6) + cart(2, 6))
-         sphr([2, 3, 5], 3) = 3 * cart([5, 6, 4], 6)
-         sphr(4, 3) = 1.5_wp * (cart(1, 6) - cart(2, 6))
-         sphr(1, 4) = s3_4 * (cart(3, 1) - cart(3, 2)) &
-            & - s3 * 0.25_wp * (cart(1, 1) - cart(1, 2) + cart(2, 1) - cart(2, 2))
-         sphr([2, 3, 5], 4) = 1.5_wp * (cart([5, 6, 4], 1) - cart([5, 6, 4], 2))
-         sphr(4, 4) = 0.75_wp * (cart(1, 1) - cart(2, 1) - cart(1, 2) + cart(2, 2))
-         sphr(1, 5) = s3 * cart(3, 4) - s3_4 * (cart(1, 4) + cart(2, 4))
-         sphr([2, 3, 5], 5) = 3 * cart([5, 6, 4], 4)
-         sphr(4, 5) = 1.5_wp * (cart(1, 4) - cart(2, 4))
+         sphr = matmul(dtrafo, matmul(cart, transpose(dtrafo)))
+         ! sphr(1, 1) = cart(3, 3) &
+            ! & - 0.5_wp * (cart(3, 1) + cart(3, 2) + cart(1, 3) + cart(2, 3)) &
+            ! & + 0.25_wp * (cart(1, 1) + cart(1, 2) + cart(2, 1) + cart(2, 2))
+         ! sphr([2, 3, 5], 1) = s3 * cart([5, 6, 4], 3) &
+            ! & - s3_4 * (cart([5, 6, 4], 1) + cart([5, 6, 4], 2))
+         ! sphr(4, 1) = s3_4 * (cart(1, 3) - cart(2, 3)) &
+            ! & - s3 * 0.25_wp * (cart(1, 1) - cart(2, 1) + cart(1, 2) - cart(2, 2))
+         ! sphr(1, 2) = s3 * cart(3, 5) - s3_4 * (cart(1, 5) + cart(2, 5))
+         ! sphr([2, 3, 5], 2) = 3 * cart([5, 6, 4], 5)
+         ! sphr(4, 2) = 1.5_wp * (cart(1, 5) - cart(2, 5))
+         ! sphr(1, 3) = s3 * cart(3, 6) - s3_4 * (cart(1, 6) + cart(2, 6))
+         ! sphr([2, 3, 5], 3) = 3 * cart([5, 6, 4], 6)
+         ! sphr(4, 3) = 1.5_wp * (cart(1, 6) - cart(2, 6))
+         ! sphr(1, 4) = s3_4 * (cart(3, 1) - cart(3, 2)) &
+            ! & - s3 * 0.25_wp * (cart(1, 1) - cart(1, 2) + cart(2, 1) - cart(2, 2))
+         ! sphr([2, 3, 5], 4) = 1.5_wp * (cart([5, 6, 4], 1) - cart([5, 6, 4], 2))
+         ! sphr(4, 4) = 0.75_wp * (cart(1, 1) - cart(2, 1) - cart(1, 2) + cart(2, 2))
+         ! sphr(1, 5) = s3 * cart(3, 4) - s3_4 * (cart(1, 4) + cart(2, 4))
+         ! sphr([2, 3, 5], 5) = 3 * cart([5, 6, 4], 4)
+         ! sphr(4, 5) = 1.5_wp * (cart(1, 4) - cart(2, 4))
       case(3)
          sphr = matmul(ftrafo, matmul(cart, transpose(dtrafo)))
       case(4)
````
</details>

**Comment by thfroitzheim** [comment] 2024-07-30 18:06
This is now fixed.

**Closed as completed by thfroitzheim** 2024-07-30 18:06 UTC
Labels: bug
